#!/usr/bin/fish

# Start sxhkd if it isn't already
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config focus_follows_pointer  true
bspc config pointer_follows_focus  true

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Thunar state=floating

picom &
~/.fehbg &
eww open bar &

